In [1]:
import os 
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from pathlib import Path
import math
from sklearn.feature_extraction import text
import random
import numpy as np

In [2]:
import re
import nltk
from sklearn.datasets import load_files
nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/ravneet/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
data = load_files(os.getcwd() + "/Datasets")
X, y = data.data, data.target

In [4]:
data.target_names

['Artificial Intelligence', 'Blockchain', 'Internet of Things']

In [5]:
X

[b'\n\n\n\nArtificial Intelligence \xe2\x80\x93 What it is and why it matters | SAS\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSolutionsBy IndustryBankingCommunicationsEducationPublic SectorHealth CareInsuranceLife SciencesManufacturingRetailSmall & Midsize BusinessUtilitiesAll IndustriesBy Technology & TopicAdvanced AnalyticsAI & Machine LearningCloud ComputingCOVID-19Marketing AnalyticsData ManagementFraud & Security IntelligenceInternet of Things (IoT)Open IntegrationOperationalizing AnalyticsRisk ManagementAll Technologies & TopicsBy ProductSAS ViyaSAS Customer Intelligence 360SAS Detection & InvestigationSAS Model ManagerSAS Visual AnalyticsSAS Visual Data Mining & Machine LearningSAS Visual ForecastingAll ProductsFree Software TrialsBy RoleDevelopersJob SeekersNovice UsersPartnersSmall & Midsize BusinessStudents & ProfessorsThought LeadersTry / BuyFree Software TrialsCOVID-19 Data Discovery EnvironmentEvent Stream ProcessingSAS 

In [6]:
y

array([0, 2, 1, 1, 2, 2, 2, 1, 1, 2, 0, 1, 0, 1, 2, 2, 0, 2, 0, 0, 1, 1,
       0, 0, 2, 0, 0, 2, 1, 1])

In [7]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /Users/ravneet/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [8]:
documents = []

from nltk.stem import WordNetLemmatizer
stemmer = WordNetLemmatizer()

for sen in range(0, len(X)):
    document = re.sub('(?<=[A-Za-z])(?=[A-Z][a-z])', ' ', str(X[sen]))
    # Remove all the special characters
    document = re.sub(r'\W', ' ', document)
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Removing prefixed 'b'
    document = re.sub("n ", "", document)
    
    # Converting to Lowercase
    document = document.lower()
    
    document = re.sub(r'(\s)x\w+', r'\1', document)
    
    # Lemmatization
    document = document.split()
    

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)
    
documents

['artificial intelligence what it is and why it matter sa solution by industry banking communication educatiopublic sector health care insurance life science manufacturing retail small midsize business utility all industry by technology topic advanced analyticsai machine learning cloud computingcovid 19marketing analytics data management fraud security intelligence internet of thing iot opeintegratiooperationalizing analytics risk management all technology topic by productsas viyasas customer intelligence 360sas detectioinvestigationsas model managersas visual analyticssas visual data mining machine learningsas visual forecasting all product free software trial by role developer job seeker novice user partner small midsize business student professor thought leader try buy free software trialscovid 19 data discovery environment event stream processingsas developer experience with opesource sa machine learning osas analytics cloudsas visual analyticssas visual data mining machine learnin

In [9]:
len(documents)

30

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(stop_words=stopwords.words('english'))
X_train_counts = count_vect.fit_transform(documents)
X_train_counts.shape

(30, 20763)

In [11]:
from sklearn.feature_extraction import text

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfconverter = TfidfVectorizer(stop_words=stopwords.words('english'))
X_train_tf = tfidfconverter.fit_transform(documents).toarray()

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train_tf, y, test_size=0.2, random_state=0, shuffle = True)

In [14]:
X_train.shape

(24, 20763)

In [15]:
X_test.shape

(6, 20763)

In [16]:
y_train.shape

(24,)

In [17]:
y_test.shape

(6,)

# GaussianNB

In [18]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [19]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[2 0 0]
 [1 2 0]
 [0 0 1]]
0.8333333333333334


# Test

In [20]:
file_names = []
count = 0
path = os.getcwd() + "/Test"
for dirpath, dirnames, filenames in os.walk(path):  # getcwd() for current work dir
    file_names = filenames

file_content = []
for file_name in file_names:
    if ('.txt' in file_name):
        file_path = path+"/"+file_name
        file = open(file_path)
        txt = file.read()
        file.close()

        file_content.append(txt)
    

In [21]:
file_names

['The Internet of Things (IoT): An Overview - Investopedia.txt',
 'The strategic business value of the blockchain market | McKinsey.txt',
 'Explainer: What is a blockchain? | MIT Technology Review.txt',
 '.DS_Store',
 'Artificial Intelligence - Journal - Elsevier.txt',
 'Internet Of Things (iot) - Gartner.txt',
 '3 Things AI Can Already Do for Your Company.txt',
 'Artificial Intelligence and the Future of Humans | Pew Research Center.txt',
 'Artificial intelligence is evolving all by itself | Science | AAAS.txt',
 'What is the Blockchain? Explaining the Tech Behind Cryptocurrencies.txt',
 'What Is the Internet of Things (IoT)? | Oracle Canada.txt',
 'What Is Blockchain? The Complete WIRED Guide | WIRED.txt',
 'Internet of Things Inc.: Artificial Intelligence Company.txt']

In [22]:
new_documents = []

from nltk.stem import WordNetLemmatizer
stemmer = WordNetLemmatizer()

for sen in range(0, len(file_content)):
    document = re.sub('(?<=[A-Za-z])(?=[A-Z][a-z])', ' ', str(file_content[sen]))
    # Remove all the special characters
    document = re.sub(r'\W', ' ', document)
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Removing prefixed 'b'
    document = re.sub("n ", "", document)
    
    # Converting to Lowercase
    document = document.lower()
    
    document = re.sub(r'(\s)x\w+', r'\1', document)
    
    # Lemmatization
    document = document.split()
    

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    new_documents.append(document)
    
new_documents

['the internet of thing iot aoverview educatiogeneral dictionary economics corporate finance roth ira stock mutual fund et f 401 investing trading investing essential fundamental analysis portfolio management trading essential technical analysis risk management market news company news market news trading news political news trend popular stock apple aapl tesla tsla amazoamzn amd amd facebook fb netflix nflx simulator simulator create aaccount joigame my simulator my game create game your money personal finance wealth management budgeting saving banking credit card home ownership retirement planning tax insurance review rating best online broker best saving account best home warranty best credit card best personal loan best student loan best life insurance best auto insurance advisor your practice practice management continuing educatiofinancial advisor career investopedia 100 wealth management portfolio constructiofinancial planning academy popular course investing for beginner become

In [23]:
len(new_documents)

12

In [24]:
X_new_counts = count_vect.transform(new_documents)

In [25]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_new_counts)
X_new_tf = tf_transformer.transform(X_new_counts)

In [26]:
X_new_tf.shape

(12, 20763)

In [27]:
predicted = classifier.predict(X_new_tf.toarray())

count = 1
for doc, category in zip(new_documents, predicted):
    print('%d => %s' % (count, data.target_names[category]))
    count+=1

1 => Internet of Things
2 => Artificial Intelligence
3 => Blockchain
4 => Artificial Intelligence
5 => Internet of Things
6 => Artificial Intelligence
7 => Artificial Intelligence
8 => Artificial Intelligence
9 => Blockchain
10 => Internet of Things
11 => Blockchain
12 => Internet of Things


In [28]:
file_names

['The Internet of Things (IoT): An Overview - Investopedia.txt',
 'The strategic business value of the blockchain market | McKinsey.txt',
 'Explainer: What is a blockchain? | MIT Technology Review.txt',
 '.DS_Store',
 'Artificial Intelligence - Journal - Elsevier.txt',
 'Internet Of Things (iot) - Gartner.txt',
 '3 Things AI Can Already Do for Your Company.txt',
 'Artificial Intelligence and the Future of Humans | Pew Research Center.txt',
 'Artificial intelligence is evolving all by itself | Science | AAAS.txt',
 'What is the Blockchain? Explaining the Tech Behind Cryptocurrencies.txt',
 'What Is the Internet of Things (IoT)? | Oracle Canada.txt',
 'What Is Blockchain? The Complete WIRED Guide | WIRED.txt',
 'Internet of Things Inc.: Artificial Intelligence Company.txt']